# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build ASP.Net Core app - bbxBE
#and deploy, to Azure Web App

on:
  push:
    branches:
      - ci_cd_testing_branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - name: Checkout from repository
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        uses: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
        # --no-restore nem kell majd?
      
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
